name: kata_util
description: A starting point for Dart libraries or applications.
version: 0.0.3
author: John Evans <prujohn@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: "^0.11.3+2"
  logging: "^0.11.2"